services:
  ms-user:
   container_name: ms-user
   build:
     context: ./User
   ports:
     - 3000:8080

  front:
    build: ./frontend
    container_name: ms-front
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 4200:4200
    depends_on:
      - ms-user
